### ISSUE TITLE
[Issue] Hardcoded value

### ISSUE THREAD

**Issue by gtrabanco** [boostchicken/lol#25]
https://github.com/boostchicken/lol/blob/7d68dbb13d1a70932ed17a4442adcbbdf9f50fbe/browser/boostchicken-omnilol/src/index.js#L5

I know this is your personal project, but, shouldn't that line to be configured instead of hardcoded?

**Comment by boostchicken** [comment]
I am lazy! Yes you are correct, let me fix!  ANd its sorta personal, but it is out there for public consumption. thanks for the hjeads up

**Comment by boostchicken** [comment]
I make a quick hack so you can use the omnibox to config that URL, check out the PR and the latest release, let me know if that works for you.
